export const LANGUAGES = [
  { label: "Italian", code: "it", direction: "ltr" },
  { label: "Arabic", code: "ar", direction: "rtl" },
  { label: "Farsi", code: "fa", direction: "rtl" },
  { label: "French", code: "fr", direction: "ltr" },
];

export const SAMPLE_CARDS = [
  {
    id: "it-ancora",
    language: "Italian",
    languageCode: "it",
    targetText: "ancora",
    translation: "still / again",
    phoneticSpelling: "ahn-KOH-rah",
    example: "Sto ancora imparando.",
    exampleTranslation: "I am still learning.",
  },
  {
    id: "it-va-bene",
    language: "Italian",
    languageCode: "it",
    targetText: "va bene",
    translation: "okay / that works",
    phoneticSpelling: "vah BEH-neh",
    example: "Va bene, ci vediamo domani.",
    exampleTranslation: "Okay, I will see you tomorrow.",
  },
  {
    id: "ar-shukran",
    language: "Arabic",
    languageCode: "ar",
    targetText: "شكرا",
    translation: "thank you",
    phoneticSpelling: "SHOO-krahn",
    example: "شكرا على المساعدة.",
    exampleTranslation: "Thank you for the help.",
  },
  {
    id: "ar-min-fadlik",
    language: "Arabic",
    languageCode: "ar",
    targetText: "من فضلك",
    translation: "please",
    phoneticSpelling: "min FAD-lak",
    example: "افتح الباب من فضلك.",
    exampleTranslation: "Open the door, please.",
  },
  {
    id: "fa-salaam",
    language: "Farsi",
    languageCode: "fa",
    targetText: "سلام",
    translation: "hello",
    phoneticSpelling: "sah-LAHM",
    example: "سلام، حال شما چطور است؟",
    exampleTranslation: "Hello, how are you?",
  },
  {
    id: "fa-lotfan",
    language: "Farsi",
    languageCode: "fa",
    targetText: "لطفا",
    translation: "please",
    phoneticSpelling: "lot-FAHN",
    example: "لطفا دوباره بگویید.",
    exampleTranslation: "Please say it again.",
  },
  {
    id: "fr-bientot",
    language: "French",
    languageCode: "fr",
    targetText: "bientôt",
    translation: "soon",
    phoneticSpelling: "byen-TOH",
    example: "Le train arrive bientôt.",
    exampleTranslation: "The train is arriving soon.",
  },
  {
    id: "fr-ca-marche",
    language: "French",
    languageCode: "fr",
    targetText: "ça marche",
    translation: "that works / okay",
    phoneticSpelling: "sah marsh",
    example: "On se voit à huit heures ? Ça marche.",
    exampleTranslation: "We meet at eight? That works.",
  },
];
