export const LANGUAGES = [
  { label: "Spanish", code: "es" },
  { label: "French", code: "fr" },
  { label: "German", code: "de" },
  { label: "English", code: "en" },
];

export const SAMPLE_CARDS = [
  {
    id: "es-todavia",
    language: "Spanish",
    languageCode: "es",
    targetText: "todavia",
    translation: "still / yet",
    phoneticSpelling: "toh-dah-VEE-ah",
    example: "Todavia estoy aprendiendo.",
    exampleTranslation: "I am still learning.",
  },
  {
    id: "es-me-da-igual",
    language: "Spanish",
    languageCode: "es",
    targetText: "me da igual",
    translation: "it does not matter to me",
    phoneticSpelling: "meh dah ee-GWAHL",
    example: "Me da igual si caminamos o tomamos el bus.",
    exampleTranslation: "It does not matter to me if we walk or take the bus.",
  },
  {
    id: "fr-bientot",
    language: "French",
    languageCode: "fr",
    targetText: "bientot",
    translation: "soon",
    phoneticSpelling: "byen-TOH",
    example: "Le train arrive bientot.",
    exampleTranslation: "The train is arriving soon.",
  },
  {
    id: "fr-ca-marche",
    language: "French",
    languageCode: "fr",
    targetText: "ca marche",
    translation: "that works / okay",
    phoneticSpelling: "sah marsh",
    example: "On se voit a huit heures ? Ca marche.",
    exampleTranslation: "We meet at eight? That works.",
  },
  {
    id: "de-genau",
    language: "German",
    languageCode: "de",
    targetText: "genau",
    translation: "exactly",
    phoneticSpelling: "guh-NOW",
    example: "Genau, das habe ich gemeint.",
    exampleTranslation: "Exactly, that is what I meant.",
  },
  {
    id: "de-keine-sorge",
    language: "German",
    languageCode: "de",
    targetText: "keine Sorge",
    translation: "do not worry",
    phoneticSpelling: "KAI-nuh ZOR-guh",
    example: "Keine Sorge, ich helfe dir.",
    exampleTranslation: "Do not worry, I will help you.",
  },
  {
    id: "en-by-the-way",
    language: "English",
    languageCode: "en",
    targetText: "by the way",
    translation: "used to add a related thought",
    phoneticSpelling: "bye thuh way",
    example: "By the way, your pronunciation is improving.",
    exampleTranslation: "By the way, your pronunciation is improving.",
  },
  {
    id: "en-gradually",
    language: "English",
    languageCode: "en",
    targetText: "gradually",
    translation: "slowly over time",
    phoneticSpelling: "GRA-joo-uh-lee",
    example: "You will gradually remember more words.",
    exampleTranslation: "You will gradually remember more words.",
  },
];
